name: Detection

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents overwriting GitHub token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Check Python version
        run: python --version

      - name: Check installed packages
        run: pip list

      - name: Run API detection script
        run: python detection.py

      - name: Commit and push if files changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add api_list.csv log.txt
          git diff --cached --quiet || (git commit -m "Updated API list and log file" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
